media:
  input: assets
  output: static
content:
  - name: posts
    label: Post
    type: collection
    path: content/posts
    view:
      fields: [title, description, date, author]
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean, default: true }
      - { name: categories, label: Category, type: string }
      - { name: author, label: Author, type: string }
      - { name: featured_image, label: Header, type: image }
      - { name: body, label: Body, type: rich-text }
      
      
