baseURL = 'https://example.org/'
DefaultContentLanguage= 'es'
languageCode = 'es-mx'
title = 'Curcubita'
theme = 'diary'
copyright = 'Curcubita'

[params]
   subtitle = "Semillas del pensar"
   enableReadingTime=true   
   disableToC=true

[taxonomies]
   tag = "tags"
   colaborador = "colaboradores"
   categoria = "categorias"

[[menu.main]]
   url = "/posts"
   name = "Archivo"
   weight = 1
[[menu.main]]
   url = "/zines"
   name = "Zines"
   weight = 2
[[menu.main]]
   url = "/categorias"
   name = "Categorias"
   weight = 3
[[menu.main]]
   url = "/tags"
   name = "Tags"
   weight = 4
[[menu.main]]
   url = "/about"
   name = "Sobre Nosotros"
   weight = 5
   
