baseURL = 'https://curcubita.art/'
DefaultContentLanguage= 'es'
languageCode = 'es-mx'
title = 'Curcubita'
theme = 'diary'
copyright = 'Curcubita'

[params]
   subtitle = "Semillas culturales"
   enableReadingTime=true   
   disableToC=true

[taxonomies]
   category = "categories"
   tag = "tags"

[[menu.main]]
   url = "/posts"
   name = "Archivo"
   weight = 1
[[menu.main]]
   url = "/categories"
   name = "Categorias"
   weight = 2
[[menu.main]]
   url = "/tags"
   name = "Tags"
   weight = 3
